### ISSUE TITLE
Animal crossing 2.0+ crashes when adding a 2nd player 

### ISSUE THREAD

**Issue by kane91z** [rdmrocha/linkalho#25] opened 2022-01-17 07:24 UTC
Been trying to figure this out and noticed that if I un-link the fake accounts with linkalho the problem goes away, but if I re-link the atmosphere crash returns.

**Comment by rdmrocha** [comment] 2022-01-27 23:50
Which version of atmosphere+HorizonOS are you running? 
Could not reproduce the issue running vanilla 13.2.1 + Atmos 1.2.6 + Hekate 5.7.0 on a freshly formatted system with Animal crossing + 2.0.4 update + Happy Home Paradise DLC

**Comment by kane91z** [comment] 2022-01-28 07:22
Right now I'm running Atmosphère 1.25 and Horizon 13.2. I have 2 switches running this and both have the same issue. Found posts on reddit and gbatemp with other's complaining about the same issue. ScriesM said the issue involved piracy so he wouldn't look into it. I should probably clarify that its not having a second player play on the island but playing co-op. I'll try updating one of my switches tonight to 13.2.1 and Atmosphère 1.2.6 and see if it persists.

**Comment by rdmrocha** [comment] 2022-08-28 21:47
Co-op requires connection to N servers. It's outside the scope of this homebrew since the created linked users will be invalid in regards to what N is concerned.

**Closed by rdmrocha** 2022-08-28 21:47 UTC
