### ISSUE TITLE
Makefile is Broken

### ISSUE THREAD

**Issue by TTghostsemir** [rdmrocha/linkalho#37] opened 2023-03-31 22:49 UTC
Hello, i have tried to compile Linkalho but the Makefile is Broken. 
Can you please fix the Makefile?

**Comment by TTghostsemir** [comment] 2023-03-31 22:49
![grafik](https://user-images.githubusercontent.com/102698694/229246111-924de448-3d56-4647-904a-cf4127e05d66.png)

**Comment by rdmrocha** [comment] 2023-04-06 09:07
Makefile works fine on both Linux and MacOS systems. 
Make sure you're using a version of 'rm' that supports the -r (recursive) and -f (force) as that appears to be your issue.
Closing as this is not a bug but rather a misconfiguration on your environment

**Closed by rdmrocha** 2023-04-06 09:07 UTC

**Comment by BeckysFootSlave** [comment] 2023-04-17 16:49
Getting the same error on Windows 11 with Msys2!

Could you kick stupid me into the right direction?
Would be awesome!

Thank you for your time!

**Comment by TTghostsemir** [comment] 2023-04-17 17:02
@rdmrocha
